name: Adds all new issues to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/yalla-coop/projects/1
          github-token: ${{ secrets.AUTO_PROJECT }}
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/yalla-coop/projects/12
          github-token: ${{ secrets.AUTO_PROJECT }}
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/yalla-coop/projects/47
          github-token: ${{ secrets.AUTO_PROJECT }}
